### ISSUE TITLE
Set Up Kamban Project

### ISSUE THREAD

**Issue by carlosmuerto** [carlosmuerto/React-Group-Project#26]
# Set Up Kamban Project

we are 2 students
 - @carlosmuerto 
 - @GloireIrenge

#### [Full README](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/setup_kanban_board.md)

**Comment by KDlamini** [comment]
### Hi team @carlosmuerto, @GloireIrenge 🙋‍♀️,  

Excellent work! 💯 
You have done a great job setting up your kanban board according to the project requirements. 🎊
Your task is complete!
Congratulations!!!

# Status: Approved ✔️ 

![LeonardoInGatsby](https://user-images.githubusercontent.com/38088818/192627792-be17f6a7-1907-4dfd-bedb-4eac6ef4b520.gif)

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
